on:
  workflow_dispatch:

jobs:
  job1:
    name: Do some secret stuff
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run some things
        run: echo "${USERNAME}:${PASSWORD}" | base64
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
